CREATE USER SOE   IDENTIFIED BY soe   PROFILE DEFAULT   ACCOUNT UNLOCK;
  -- 2 Roles for SOE 
  GRANT CONNECT TO SOE;
  GRANT RESOURCE TO SOE;
  ALTER USER SOE DEFAULT ROLE ALL;
  -- 9 System Privileges for SOE 
  BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'SOE', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
  GRANT ALTER SESSION TO SOE;
  GRANT ALTER SYSTEM TO SOE;
  GRANT ANALYZE ANY TO SOE;
  GRANT ANALYZE ANY DICTIONARY TO SOE;
  GRANT CREATE JOB TO SOE;
  GRANT CREATE VIEW TO SOE;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'SOE',
  ADMIN_OPTION => FALSE);
END;
/
  GRANT MANAGE SCHEDULER TO SOE;
  GRANT EXECUTE ON SYS.DBMS_LOCK TO SOE;