CREATE ROLE RECOVERY_CATALOG_OWNER NOT IDENTIFIED;

-- Object privileges granted to RECOVERY_CATALOG_OWNER
GRANT EXECUTE ON SYS.DBMS_LOCK TO RECOVERY_CATALOG_OWNER;

-- Grants of objects owned by RC_OWNER to the RECOVERY_CATALOG_OWNER role are at the the end of the schema script.
-- System privileges granted to RECOVERY_CATALOG_OWNER
GRANT CREATE SYNONYM TO RECOVERY_CATALOG_OWNER;
GRANT CREATE CLUSTER TO RECOVERY_CATALOG_OWNER;
GRANT ALTER SESSION TO RECOVERY_CATALOG_OWNER;
GRANT CREATE DATABASE LINK TO RECOVERY_CATALOG_OWNER;
GRANT CREATE PROCEDURE TO RECOVERY_CATALOG_OWNER;
GRANT CREATE TRIGGER TO RECOVERY_CATALOG_OWNER;
GRANT CREATE TABLE TO RECOVERY_CATALOG_OWNER;
GRANT CREATE SESSION TO RECOVERY_CATALOG_OWNER;
GRANT CREATE TYPE TO RECOVERY_CATALOG_OWNER;
GRANT CREATE VIEW TO RECOVERY_CATALOG_OWNER;
GRANT CREATE SEQUENCE TO RECOVERY_CATALOG_OWNER;


--
-- RC_OWNER  (User) 
--
CREATE USER RC_OWNER
  IDENTIFIED BY oracle
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for RC_OWNER 
  GRANT RECOVERY_CATALOG_OWNER TO RC_OWNER;
  ALTER USER RC_OWNER DEFAULT ROLE ALL;
